//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddressType
    {
        public AddressType()
        {
            this.ProfileAddresses = new HashSet<ProfileAddress>();
        }
    
        public int AddressTypeId { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<ProfileAddress> ProfileAddresses { get; set; }
    }
}
