//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhoneType
    {
        public PhoneType()
        {
            this.ProfilePhones = new HashSet<ProfilePhone>();
        }
    
        public int PhoneTypeId { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<ProfilePhone> ProfilePhones { get; set; }
    }
}
